#!/usr/bin/env php
<?php

echo "Initializing Git Submodules\n";
exec('git submodule update --init --recursive');

echo "Building Silex\n";
exec('./silex/compile');

echo "Creating directories\n";

if (mkdir(__DIR__.'/log');) {
    echo "* Log directory created";
}

if (mkdir(__DIR__.'/cache');) {
    echo "* Cache directory created";
}

