#!/usr/bin/env php
<?php

echo "\nInitializing Git Submodules\n";
echo "------------------------------\n";
exec('git submodule update --init --recursive');

echo "\nCompiling Silex\n";
echo "------------------------------\n";
exec('./silex/compile');
exec('mv silex.phar silex/silex.phar');
echo "Done!\n";

echo "\nCreating directories\n";
echo "------------------------------\n";

if (mkdir(__DIR__.'/log')) {
    exec('chmod 0775 log'); 
    echo "* Log directory created\n";
}

if (mkdir(__DIR__.'/cache')) {
    exec('chmod 0775 cache');
    echo "* Cache directory created\n";
}

